import org.apache.tools.ant.taskdefs.condition.Os

plugins {
    id 'application'
}

apply from: 'versions.gradle'

group   = 'ru.mipt.bit'
version = '1.0-SNAPSHOT'
def gdxVersion = '1.12.0'

application {

    mainClass = 'ru.mipt.bit.platformer.GameDesktopLauncher'

    if (Os.isFamily(Os.FAMILY_MAC)) {
        applicationDefaultJvmArgs = ['-XstartOnFirstThread']
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation "com.badlogicgames.gdx:gdx:$gdxVersion"
    implementation "com.badlogicgames.gdx:gdx-backend-lwjgl3:$gdxVersion"
    runtimeOnly "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-desktop"
}
